import type { ProductSurfaceAssignment, TierBoundaryCase } from './client.js';

export const REGISTERED_TOOL_NAMES = [
  'route_intent_wizard',
  'plan_stack_bootstrap',
  'wizard_new_site_lite',
  'wizard_stack_bootstrap',
  'wizard_relaunch_lite',
  'wizard_optimization_lite',
  'wizard_extension_lite',
  'run_free_wizard_preset',
  'run_free_guided_transition',
  'plan_rebuild_strategy',
  'critique_rebuild_strategy',
  'assess_site',
  'plan_brand_adaptation',
  'queue_change',
  'list_change_queue',
  'review_change',
  'apply_change',
  'plan_premium_library_usage',
  'import_premium_library_asset',
  'import_external_data',
  'mass_export',
  'route_advanced_scenario',
  'advanced_creator_mode',
  'get_template_data',
  'update_template_data',
  'extract_sections',
  'suggest_pipeline_path',
  'extract_design_tokens',
  'get_destination_capabilities',
  'get_site_fingerprint',
  'get_global_styles',
  'set_global_colors',
  'set_global_typography',
  'list_templates',
  'get_template',
  'create_template',
  'update_template',
  'delete_template',
  'rename_template',
  'duplicate_template',
  'bulk_rename',
  'list_by_type',
  'set_category',
  'set_tags',
  'audit_library',
  'critique_elementor_output',
  'list_elementor_pages',
  'get_page_data',
  'save_page_section_as_template',
  'update_page_data',
  'compose_page_from_templates',
  'save_full_page_as_template',
  'set_site_context',
  'get_site_context',
  'get_recommendations',
  'get_advanced_recommendations',
  'plan_advanced_upgrade_path',
  'explain_recommendation',
  'get_site_info',
  'list_sites',
  'switch_site',
  'search_stock_images',
  'generate_ai_image',
  'list_premium_library_assets',
  'inspect_premium_library_asset',
  'sideload_stock_image',
  'validate_elementor_write',
  'set_site_logo',
  'wizard_brand_setup',
  'creator_mode',
  'wizard_theme_builder',
  'list_menus',
  'create_menu',
  'delete_menu',
  'list_menu_items',
  'create_menu_item',
  'update_menu_item',
  'delete_menu_item',
  'list_menu_locations',
  'assign_menu_location',
  'create_page',
  'create_post',
  'update_post_meta',
  'delete_post',
  'list_taxonomies',
  'create_term',
  'update_term',
  'delete_term',
  'list_post_types',
  'list_media',
  'get_media',
  'update_media',
  'delete_media',
  'audit_unused_media',
  'flush_elementor_cache',
  'get_performance_report',
  'get_seo_meta',
  'get_site_settings',
  'optimize_elementor_assets',
  'clean_database',
  'update_seo_meta',
  'update_site_settings',
  'create_form_light',
  'create_form_advanced',
  'list_form_templates',
  'list_forms',

  'migrate_form',
  'analyze_translation_coverage',
  'batch_translate_strings',
  'translate_media_metadata',
  'get_ally_status',
  'get_ally_scan_results',
  'trigger_ally_scan',
  'apply_ally_fix',
  'scan_accessibility',
  'get_lms_status',
  'list_lms_courses',
  'get_lms_course_structure',
  'get_charity_status',
  'list_charity_forms',
  'get_charity_stats',
  'detect_booking_plugin',
  'list_bookings',
  'get_booking_stats',
  'wizard_booking',
  'wizard_acf',
  'wizard_forms',
  'wizard_comments',
  'wizard_multi',
  'wizard_plugin',
  'wizard_export',
  'wizard_health',
  'wizard_ally',
  'wizard_lms',
  'wizard_charity',
  'get_voxel_status',
  'list_voxel_post_types',
  'get_voxel_post_type',
  'list_voxel_taxonomies',
  'list_voxel_product_types',
  'get_voxel_settings',
  'get_voxel_health',
  'get_cache_recommendation',
  'diagnose_issue',
  'read_error_log',
  'test_plugin_conflict',
  'list_amelia_services',
  'get_amelia_service',
  'create_amelia_service',
  'update_amelia_service',
  'delete_amelia_service',
  'list_amelia_appointments',
  'get_amelia_appointment',
  'create_amelia_appointment',
  'update_amelia_appointment',
  'delete_amelia_appointment',
  'list_products',
  'get_product',
  'create_product',
  'update_product',
  'delete_product',
  'list_orders',
  'get_order',
  'update_order_status',
  'list_product_categories',
  'generate_critical_css',
  'manage_product_category',
  'get_store_settings',
  'update_store_settings',
  'setup_woocommerce_pages',
  'list_active_addons',
  'detect_essential_addons',
  'list_ea_widgets',
  'analyze_ea_usage',
  'optimize_ea_config',
  'wizard_essential_addons',
  'detect_crocoblock',
  'list_jet_post_types',
  'list_jet_listings',
  'analyze_jet_usage',
  'get_jet_query_builders',
  'wizard_crocoblock',
  'detect_uae',
  'list_uae_widgets',
  'analyze_uae_usage',
  'wizard_uae',
  'detect_powerpack',
  'list_powerpack_widgets',
  'analyze_powerpack_usage',
  'optimize_powerpack_config',
  'wizard_powerpack',
  'detect_happy_addons',
  'list_happy_addons_widgets',
  'analyze_happy_addons_usage',
  'optimize_happy_addons_config',
  'wizard_happy_addons',
  'detect_elementskit',
  'list_elementskit_widgets',
  'analyze_elementskit_usage',
  'optimize_elementskit_config',
  'wizard_elementskit',
  'detect_premium_addons',
  'list_premium_addons_widgets',
  'analyze_premium_addons_usage',
  'optimize_premium_addons_config',
  'wizard_premium_addons',
  'detect_the_plus_addons',
  'list_the_plus_addons_widgets',
  'analyze_the_plus_addons_usage',
  'optimize_the_plus_addons_config',
  'wizard_the_plus_addons',
  'analyze_addon_overlap',
  'widget_census',
  'addon_ecosystem_wizard',
] as const;

export type RegisteredToolName = (typeof REGISTERED_TOOL_NAMES)[number];

export const TOOL_TIER_ASSIGNMENTS: ProductSurfaceAssignment[] = [
  {
    id: 'route_intent_wizard',
    label: 'Intent wizard routing',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free needs a scenario-first front door that turns user intent into the next sensible guided path.',
  },
  {
    id: 'plan_stack_bootstrap',
    label: 'Stack bootstrap front door',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should act as a 360-degree starting point even when Elementor is not installed yet.',
    dependsOn: ['route_intent_wizard'],
  },
  {
    id: 'wizard_new_site_lite',
    label: 'New Site Lite wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free needs a concrete new-site runtime wizard for idea-first and brand-first entry states.',
    dependsOn: ['route_intent_wizard', 'wizard_brand_setup', 'creator_mode'],
  },
  {
    id: 'wizard_stack_bootstrap',
    label: 'Stack bootstrap wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free needs a concrete bootstrap runtime wizard that turns routing into phased baseline, foundation, and first-build actions.',
    dependsOn: ['plan_stack_bootstrap', 'wizard_brand_setup', 'creator_mode'],
  },
  {
    id: 'wizard_relaunch_lite',
    label: 'Relaunch Lite wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support preservation-aware relaunch lite work before deeper structural Advanced execution begins.',
    dependsOn: ['route_intent_wizard', 'get_recommendations', 'creator_mode'],
  },
  {
    id: 'wizard_optimization_lite',
    label: 'Optimization Lite wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should translate optimization intent into a real low-risk guided loop instead of stopping at raw recommendations.',
    dependsOn: ['route_intent_wizard', 'get_recommendations', 'explain_recommendation'],
  },
  {
    id: 'wizard_extension_lite',
    label: 'Extension Lite wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support restrained, support-aware extension work without immediately pushing users into deeper Advanced rollout.',
    dependsOn: ['route_intent_wizard', 'get_recommendations', 'creator_mode'],
  },
  {
    id: 'run_free_wizard_preset',
    label: 'Free wizard preset runner',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should begin to support limited guided execution for safe presets without turning scenario-first flows into unsafe one-click automation.',
    dependsOn: ['wizard_stack_bootstrap', 'wizard_relaunch_lite', 'wizard_optimization_lite'],
    notes: ['Only presets marked safe_execute may run directly; preview_only remains part of the guidance layer.'],
  },
  {
    id: 'run_free_guided_transition',
    label: 'Free guided transition runner',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support short scenario-aware guided transitions for its most important early paths before users are dropped into isolated tool calls.',
    dependsOn: ['run_free_wizard_preset', 'wizard_stack_bootstrap', 'wizard_optimization_lite'],
    notes: ['This chains safe and preview-only presets together without turning Free into unsafe full automation.'],
  },
  {
    id: 'assess_site',
    label: 'Site assessment',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Core Free intelligence lift and the basis for recommendations.',
  },
  {
    id: 'set_site_context',
    label: 'Set site context',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free onboarding context is part of the core guided setup.',
  },
  {
    id: 'get_site_context',
    label: 'Get site context',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free operators need visibility into stored onboarding context.',
  },
  {
    id: 'get_recommendations',
    label: 'Recommendation engine',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Prioritized recommendations are a headline Free promise.',
    dependsOn: ['assess_site', 'set_site_context'],
  },
  {
    id: 'explain_recommendation',
    label: 'Recommendation guide',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Guided next steps are part of the Free workflow surface.',
    dependsOn: ['get_recommendations'],
  },
  {
    id: 'get_advanced_recommendations',
    label: 'Advanced recommendation depth',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced needs a deeper additive recommendation layer for premium-library usage, critique, governance, and stronger workflow differentiation.',
    dependsOn: ['get_recommendations'],
  },
  {
    id: 'plan_advanced_upgrade_path',
    label: 'Advanced upgrade path planning',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced needs an honest scenario-aware upgrade and stack-shaping seam so Elementor Pro, Elementeer Advanced, and curated addon choices stay distinct.',
    dependsOn: ['get_advanced_recommendations', 'get_destination_capabilities'],
  },
  {
    id: 'get_site_fingerprint',
    label: 'Site fingerprint',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Destination understanding should remain mirror-safe and public.',
  },
  {
    id: 'get_destination_capabilities',
    label: 'Destination capabilities',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Capability transparency supports Free guidance and validation.',
    dependsOn: ['assess_site', 'get_site_fingerprint'],
  },
  {
    id: 'validate_elementor_write',
    label: 'Write validation',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Honest validation is part of the Free-safe execution layer.',
  },
  {
    id: 'get_site_info',
    label: 'Site info',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Basic operator visibility belongs in Free.',
  },
  {
    id: 'list_sites',
    label: 'List configured sites',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Agent-native setup in Free includes local multi-site config awareness.',
    notes: ['This is local operator convenience, not Studio cloud reuse.'],
  },
  {
    id: 'switch_site',
    label: 'Switch configured site',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free setup should not be artificially limited by local config switching.',
    notes: ['Local site switching is not equivalent to Studio cross-site orchestration.'],
  },
  {
    id: 'list_templates',
    label: 'List templates',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Local Elementor Library management is core Free functionality.',
  },
  {
    id: 'get_template',
    label: 'Get template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Reading local templates is part of the Free local-library surface.',
  },
  {
    id: 'create_template',
    label: 'Create template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free includes generating and assembling simple structures into the local library.',
  },
  {
    id: 'update_template',
    label: 'Update template metadata',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free must support practical local template management.',
  },
  {
    id: 'delete_template',
    label: 'Delete template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should not be crippled for local library cleanup.',
    notes: ['Governance and scoped API keys remain the safety layer.'],
  },
  {
    id: 'rename_template',
    label: 'Rename template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Naming and cleanup are essential parts of Free library hygiene.',
  },
  {
    id: 'duplicate_template',
    label: 'Duplicate template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Basic local reuse belongs in Free.',
  },
  {
    id: 'bulk_rename',
    label: 'Bulk rename templates',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support practical local-library organization, not just inspection.',
  },
  {
    id: 'plan_premium_library_usage',
    label: 'Premium library usage plan',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'This is the first provider-aware Advanced workflow for using curated premium assets without implying cloud-library behavior.',
  },
  {
    id: 'import_premium_library_asset',
    label: 'Premium library import',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced must be able to execute the curated premium-library flow through the dedicated local import seam, not just inspect and plan it.',
    dependsOn: ['inspect_premium_library_asset', 'plan_premium_library_usage'],
  },
  {
    id: 'import_external_data',
    label: 'External data import',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Import posts, pages, or products from CSV/JSON/XML files with field mapping and duplicate detection.',
    dependsOn: ['queue_change'],
  },
  {
    id: 'mass_export',
    label: 'Bulk data export',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Bulk export of posts, pages, or products as CSV/JSON with filters. Supports filtering by post_type, category, date range, status, author, etc.',
    dependsOn: ['queue_change'],
  },
  {
    id: 'route_advanced_scenario',
    label: 'Advanced scenario routing',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced needs a scenario-first private front door so deeper paid workflows present as operational routes instead of a flat extra tool shelf.',
    dependsOn: ['get_advanced_recommendations', 'advanced_creator_mode'],
  },
  {
    id: 'advanced_creator_mode',
    label: 'Advanced creator mode',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced needs a deeper orchestrated workflow mode that ties premium rollout, Theme Builder rollout, and critique loops together in one guided surface.',
    dependsOn: ['get_advanced_recommendations', 'import_premium_library_asset', 'wizard_theme_builder'],
  },
  {
    id: 'list_premium_library_assets',
    label: 'Premium library catalog',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced needs a curated asset catalog before planning or importing premium structures.',
  },
  {
    id: 'inspect_premium_library_asset',
    label: 'Premium library inspection',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Asset inspection is part of the private Advanced premium-library workflow and stays local-site operational.',
  },
  {
    id: 'get_template_data',
    label: 'Get raw template data',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Existing-block customization requires raw structure access in Free.',
  },
  {
    id: 'update_template_data',
    label: 'Update raw template data',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free includes intelligent customization of existing Elementor structures.',
  },
  {
    id: 'extract_sections',
    label: 'Extract sections',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Section extraction is part of the local customization and assembly loop.',
  },
  {
    id: 'list_by_type',
    label: 'List templates by type',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Template organization remains part of the Free local library story.',
  },
  {
    id: 'set_category',
    label: 'Set template category',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free guidance depends on usable local template metadata.',
  },
  {
    id: 'set_tags',
    label: 'Set template tags',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free creator-light flows benefit from local tag metadata.',
  },
  {
    id: 'audit_library',
    label: 'Audit template library',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Library audit is part of the Free intelligence and hygiene surface.',
  },
  {
    id: 'list_elementor_pages',
    label: 'List Elementor pages',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free includes simple page and section workflows on the current site.',
  },
  {
    id: 'get_page_data',
    label: 'Get page data',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Current-site inspection is part of Free page workflows.',
  },
  {
    id: 'save_page_section_as_template',
    label: 'Save page section as template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support extracting reusable value from existing pages.',
  },
  {
    id: 'update_page_data',
    label: 'Update page data',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Simple assembly and customization on the current site are part of Free.',
  },
  {
    id: 'compose_page_from_templates',
    label: 'Compose page from templates',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Simple page assembly is explicitly part of the Free promise.',
  },
  {
    id: 'save_full_page_as_template',
    label: 'Save full page as template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free local reuse includes preserving current-site page structures as templates.',
  },
  {
    id: 'get_global_styles',
    label: 'Get global styles',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Brand-state understanding is part of the Free brand setup loop.',
  },
  {
    id: 'set_global_colors',
    label: 'Set global colors',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Brand setup is part of the Free intelligent lift.',
  },
  {
    id: 'set_global_typography',
    label: 'Set global typography',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Brand setup is part of the Free intelligent lift.',
  },
  {
    id: 'set_site_logo',
    label: 'Set site logo',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Logo setup is part of Free onboarding and brand lift.',
  },
  {
    id: 'wizard_brand_setup',
    label: 'Brand setup wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'One of the strong Free wizard surfaces for guided onboarding.',
  },
  {
    id: 'creator_mode',
    label: 'Creator mode',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Creator Wizard Light belongs in Free as a core differentiation surface.',
    notes: ['Free surface is creator-light; deeper creator depth remains Advanced.'],
  },
  {
    id: 'wizard_theme_builder',
    label: 'Theme Builder wizard',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Theme Builder crosses from creator-light into site-wide structural workflows and should mark Advanced depth.',
  },
  {
    id: 'search_stock_images',
    label: 'Search stock images',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Media sourcing is useful workflow acceleration but not required for the Free core promise.',
  },
  {
    id: 'sideload_stock_image',
    label: 'Sideload stock image',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Operational media ingestion belongs in the deeper Advanced creation layer.',
  },
  {
    id: 'generate_ai_image',
    label: 'Generate AI image',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'AI media generation is additive creator power and should remain private to Advanced.',
  },
  {
    id: 'queue_change',
    label: 'Queue change',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Approval-oriented governance is part of stronger Advanced operational workflows.',
  },
  {
    id: 'list_change_queue',
    label: 'List change queue',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Queued review is part of Advanced operational discipline.',
  },
  {
    id: 'review_change',
    label: 'Review queued change',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Human-in-the-loop review flows belong in Advanced.',
  },
  {
    id: 'apply_change',
    label: 'Apply queued change',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Governed change application belongs in Advanced.',
  },
  {
    id: 'extract_design_tokens',
    label: 'Extract design tokens',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Token extraction is mainly valuable as input to deeper adaptation and planning flows.',
  },
  {
    id: 'plan_brand_adaptation',
    label: 'Brand adaptation plan',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Brand adaptation is a deeper workflow layer and a clear Advanced differentiator.',
    dependsOn: ['extract_design_tokens'],
  },
  {
    id: 'plan_rebuild_strategy',
    label: 'Rebuild strategy planning',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Typed planning and stronger agent-native workflow behavior belong in Advanced.',
  },
  {
    id: 'critique_rebuild_strategy',
    label: 'Rebuild strategy critique',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Strategy critique is part of the deeper Advanced operator layer.',
    dependsOn: ['plan_rebuild_strategy'],
  },
  {
    id: 'critique_elementor_output',
    label: 'Elementor output critique',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Output critique and repair guidance are deeper productivity features beyond Free validation.',
    dependsOn: ['validate_elementor_write'],
  },
  {
    id: 'suggest_pipeline_path',
    label: 'Pipeline path suggestion',
    tier: 'studio_future',
    visibility: 'future',
    kind: 'tool',
    rationale: 'Conversational control and orchestration belong to the future Studio operating mode, even if a seed exists today.',
    notes: ['Keep as an internal seam until a Studio-facing orchestration story is ready.'],
  },
  {
    id: 'list_menus',
    label: 'List navigation menus',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Menu reading is part of Free theme-structure awareness.',
  },
  {
    id: 'create_menu',
    label: 'Create navigation menu',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Menu creation is part of Free theme-structure management.',
  },
  {
    id: 'delete_menu',
    label: 'Delete navigation menu',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Menu deletion is part of Free theme-structure management (consistent with delete_template precedent).',
  },
  {
    id: 'list_menu_items',
    label: 'List menu items',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Reading menu items is part of Free theme-structure awareness.',
  },
  {
    id: 'create_menu_item',
    label: 'Create menu item',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Creating menu items is part of Free theme-structure management.',
  },
  {
    id: 'update_menu_item',
    label: 'Update menu item',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Updating menu items is part of Free theme-structure management.',
  },
  {
    id: 'delete_menu_item',
    label: 'Delete menu item',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Deleting menu items is part of Free theme-structure management.',
  },
  {
    id: 'list_menu_locations',
    label: 'List menu locations',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Reading theme menu locations is part of Free theme-structure awareness.',
  },
  {
    id: 'assign_menu_location',
    label: 'Assign menu to location',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Assigning menus to theme locations is part of Free theme-structure management.',
  },
  {
    id: 'create_page',
    label: 'Create page',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Creating WordPress pages is part of Free content management.',
  },
  {
    id: 'create_post',
    label: 'Create post',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Creating WordPress posts is part of Free content management.',
  },
  {
    id: 'update_post_meta',
    label: 'Update post meta',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Updating post metadata (slug, excerpt, featured image) is part of Free content management.',
  },
  {
    id: 'delete_post',
    label: 'Delete post',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Deleting posts is part of Free content management (governance and scoped API keys provide safety).',
  },
  {
    id: 'list_taxonomies',
    label: 'List taxonomies',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Listing taxonomies is part of Free content structure awareness.',
  },
  {
    id: 'create_term',
    label: 'Create term',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Creating taxonomy terms is part of Free content structure management.',
  },
  {
    id: 'update_term',
    label: 'Update term',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Updating taxonomy terms is part of Free content structure management.',
  },
  {
    id: 'delete_term',
    label: 'Delete term',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Deleting taxonomy terms is part of Free content structure management.',
  },
  {
    id: 'list_post_types',
    label: 'List post types',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Listing post types is part of Free content structure awareness.',
  },
  {
    id: 'list_media',
    label: 'List media',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Listing media attachments is part of Free content management.',
  },
  {
    id: 'get_media',
    label: 'Get media details',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Getting media details (including image sizes) is part of Free content management.',
  },
  {
    id: 'update_media',
    label: 'Update media metadata',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Updating alt text, title, caption, and description is part of Free content management.',
  },
  {
    id: 'delete_media',
    label: 'Delete media',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Deleting media attachments (move to trash or permanently delete) is part of Free content management.',
  },
  {
    id: 'audit_unused_media',
    label: 'Unused media audit',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced media workflows include heuristic analysis of unused attachments for library cleanup.',
  },
  {
    id: 'flush_elementor_cache',
    label: 'Flush Elementor cache',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Cache flushing is a basic maintenance operation for Elementor sites and should be part of Free.',
  },
  {
    id: 'get_performance_report',
    label: 'Get performance report',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Performance reporting helps users understand site optimization status and is part of Free intelligence.',
  },
  {
    id: 'get_seo_meta',
    label: 'Get SEO meta',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Reading SEO metadata is part of Free content management and SEO optimization workflows.',
  },
  {
    id: 'get_site_settings',
    label: 'Get site settings',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Reading WordPress core settings is part of Free site intelligence and configuration awareness.',
  },
  {
    id: 'optimize_elementor_assets',
    label: 'Optimize Elementor assets',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Asset optimization is a deeper performance workflow that belongs in Advanced tier.',
  },
  {
    id: 'clean_database',
    label: 'Clean database bloat',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Database optimization (revisions, transients, spam) is a maintenance operation with L2 governance.',
  },
  {
    id: 'get_cache_recommendation',
    label: 'Cache plugin recommendation',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Hosting-aware cache recommendation is a deeper performance optimization workflow for Advanced tier.',
  },
  {
    id: 'diagnose_issue',
    label: 'Guided troubleshooting',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Diagnostic workflows for complex issues (white screen, plugin conflicts) belong in Advanced tier.',
  },
  {
    id: 'read_error_log',
    label: 'Read error log',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Reading debug.log is part of advanced troubleshooting workflows.',
  },
  {
    id: 'test_plugin_conflict',
    label: 'Test plugin conflict',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Safe plugin conflict testing with L2 governance belongs in Advanced tier.',
  },
  {
    id: 'update_seo_meta',
    label: 'Update SEO meta',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Writing SEO metadata is part of Free content management and SEO optimization workflows.',
  },
  {
    id: 'update_site_settings',
    label: 'Update site settings',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Writing WordPress core settings is part of Free site configuration management.',
  },
  {
    id: 'create_form_light',
    label: 'Form Creation Light',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support basic form creation for Elementor forms with simple fields and email/redirect actions.',
  },
  {
    id: 'create_form_advanced',
    label: 'Form Creation Advanced',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier should support multi-step forms, conditional logic, and marketing integrations (Mailchimp, HubSpot, webhooks).',
  },

  {
    id: 'migrate_form',
    label: 'Cross-Plugin Form Migration',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier should support migrating forms from CF7, WPForms, and Gravity Forms to Elementor Forms with field mapping.',
  },
  {
    id: 'analyze_translation_coverage',
    label: 'Translation Coverage Analysis',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should provide translation gap analysis for multilingual sites (WPML/Polylang) with coverage matrix.',
  },
  {
    id: 'get_ally_status',
    label: 'Elementor Ally Detection',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should detect Elementor Ally plugin presence, version, tier, and credits for conditional tool exposure.',
  },
  {
    id: 'get_ally_scan_results',
    label: 'Ally Scan Results',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should retrieve Ally scan results merged with built‑in A11Y scanner.',
  },
  {
    id: 'trigger_ally_scan',
    label: 'Trigger Ally Scan',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier can trigger Ally scans with L2 governance (auto‑queue).',
  },
  {
    id: 'apply_ally_fix',
    label: 'Apply Ally Fix',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier can apply Ally fixes with L2 governance (auto‑queue).',
  },
  {
    id: 'scan_accessibility',
    label: 'Built-in accessibility scanner',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Built-in accessibility scanner that runs WCAG scan without Elementor Ally plugin, returns violations grouped by severity with auto-fix suggestions.',
  },
  {
    id: 'get_lms_status',
    label: 'LMS Plugin Detection',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should detect LMS plugins (LearnDash, Tutor LMS, LifterLMS) for integration recommendations.',
  },
  {
    id: 'list_lms_courses',
    label: 'List LMS Courses',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should list courses from detected LMS plugin with pagination.',
  },
  {
    id: 'get_lms_course_structure',
    label: 'Get LMS Course Structure',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should retrieve course structure (sections, lessons, quizzes) for AI-powered content adaptation.',
  },
  {
    id: 'get_charity_status',
    label: 'Charity Plugin Detection',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should detect charity/donation plugins (GiveWP, Charitable) for integration recommendations.',
  },
  {
    id: 'list_charity_forms',
    label: 'List Donation Forms',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should list donation forms from detected charity plugin with pagination.',
  },
  {
    id: 'get_charity_stats',
    label: 'Get Charity Statistics',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should retrieve overall donation statistics (total raised, donor count, average donation).',
  },
  {
    id: 'detect_booking_plugin',
    label: 'Booking Plugin Detection',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should detect booking/events plugins (Amelia, Simply Schedule Appointments, The Events Calendar) for integration recommendations.',
  },
  {
    id: 'list_bookings',
    label: 'List Bookings/Events',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should list bookings/events from detected plugin with pagination.',
  },
  {
    id: 'get_booking_stats',
    label: 'Get Booking Statistics',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free tier should retrieve booking statistics (total, upcoming, past, cancelled, popular services, peak hours, revenue).',
  },
  {
    id: 'wizard_booking',
    label: 'Booking module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Booking & Events module recommendations.',
  },
  {
    id: 'list_amelia_services',
    label: 'List Amelia Services',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier CRUD operation for listing Amelia services.',
  },
  {
    id: 'get_amelia_service',
    label: 'Get Amelia Service',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier CRUD operation for retrieving a single Amelia service.',
  },
  {
    id: 'create_amelia_service',
    label: 'Create Amelia Service',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier CRUD operation for creating a new Amelia service.',
  },
  {
    id: 'update_amelia_service',
    label: 'Update Amelia Service',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier CRUD operation for updating an existing Amelia service.',
  },
  {
    id: 'delete_amelia_service',
    label: 'Delete Amelia Service',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier CRUD operation for deleting an Amelia service.',
  },
  {
    id: 'list_amelia_appointments',
    label: 'List Amelia Appointments',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier CRUD operation for listing Amelia appointments.',
  },
  {
    id: 'get_amelia_appointment',
    label: 'Get Amelia Appointment',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier CRUD operation for retrieving a single Amelia appointment.',
  },
  {
    id: 'create_amelia_appointment',
    label: 'Create Amelia Appointment',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier CRUD operation for creating a new Amelia appointment.',
  },
  {
    id: 'update_amelia_appointment',
    label: 'Update Amelia Appointment',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier CRUD operation for updating an existing Amelia appointment.',
  },
  {
    id: 'delete_amelia_appointment',
    label: 'Delete Amelia Appointment',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced tier CRUD operation for deleting an Amelia appointment.',
  },
  {
    id: 'list_products',
    label: 'List WooCommerce Products',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: list products with pagination and filtering.',
  },
  {
    id: 'get_product',
    label: 'Get WooCommerce Product',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: retrieve a single product by ID.',
  },
  {
    id: 'create_product',
    label: 'Create WooCommerce Product',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: create a new product with basic details.',
  },
  {
    id: 'update_product',
    label: 'Update WooCommerce Product',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: update an existing product.',
  },
  {
    id: 'delete_product',
    label: 'Delete WooCommerce Product',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: delete a product (moved to trash).',
  },
  {
    id: 'list_orders',
    label: 'List WooCommerce Orders',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: list orders with pagination and filtering.',
  },
  {
    id: 'get_order',
    label: 'Get WooCommerce Order',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: retrieve a single order by ID.',
  },
  {
    id: 'update_order_status',
    label: 'Update WooCommerce Order Status',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: update order status (pending, processing, completed, etc.).',
  },
  {
    id: 'list_product_categories',
    label: 'List WooCommerce Product Categories',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: list product categories.',
  },
  {
    id: 'generate_critical_css',
    label: 'Generate Critical CSS',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced performance operation: generate critical CSS for faster page loads.',
  },
  {
    id: 'manage_product_category',
    label: 'Manage WooCommerce Product Category',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: create/update/delete product categories.',
  },
  {
    id: 'get_store_settings',
    label: 'Get WooCommerce Store Settings',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: retrieve store settings (currency, location, etc.).',
  },
  {
    id: 'update_store_settings',
    label: 'Update WooCommerce Store Settings',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: update store settings.',
  },
  {
    id: 'setup_woocommerce_pages',
    label: 'Setup WooCommerce Pages',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced e-commerce operation: create missing WooCommerce pages (shop, cart, checkout, my account).',
  },
  {
    id: 'wizard_acf',
    label: 'ACF module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for ACF (Advanced Custom Fields) module recommendations.',
  },
  {
    id: 'wizard_forms',
    label: 'Forms module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Forms module recommendations.',
  },
  {
    id: 'wizard_comments',
    label: 'Comments module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Comments module recommendations.',
  },
  {
    id: 'wizard_multi',
    label: 'Multilingual module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Multilingual module recommendations.',
  },
  {
    id: 'wizard_plugin',
    label: 'Plugin stack module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Plugin stack module recommendations.',
  },
  {
    id: 'wizard_export',
    label: 'Export module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Export module recommendations.',
  },
  {
    id: 'wizard_health',
    label: 'Site health module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Site health module recommendations.',
  },
  {
    id: 'wizard_ally',
    label: 'Accessibility module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Accessibility (Ally) module recommendations.',
  },
  {
    id: 'wizard_lms',
    label: 'LMS module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for LMS (Learning Management System) module recommendations.',
  },
  {
    id: 'wizard_charity',
    label: 'Charity module wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Charity (Donation) module recommendations.',
  },
  {
    id: 'batch_translate_strings',
    label: 'AI-powered batch string translation',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced multilingual intelligence: translate WPML/Polylang strings using AI with L2 governance.',
  },
  {
    id: 'translate_media_metadata',
    label: 'Media metadata translation',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced multilingual intelligence: translate alt text, captions, descriptions, and titles for media items with L2 governance.',
  },
  // Addon detection tools (Free)
  {
    id: 'list_active_addons',
    label: 'List active addons',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should provide visibility into installed Elementor add‑ons as part of the local ecosystem awareness.',
  },
  {
    id: 'detect_essential_addons',
    label: 'Detect Essential Addons',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should detect the presence and version of Essential Addons for Elementor (Free/Pro).',
  },
  {
    id: 'list_ea_widgets',
    label: 'List EA widgets',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should list all widgets provided by Essential Addons with activation status.',
  },
  {
    id: 'detect_crocoblock',
    label: 'Detect Crocoblock Suite',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should detect the Crocoblock / JetEngine suite and its individual plugins.',
  },
  {
    id: 'list_jet_post_types',
    label: 'List JetEngine post types',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should list custom post types created by JetEngine with field schemas.',
  },
  {
    id: 'list_jet_listings',
    label: 'List JetEngine listings',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should list JetEngine listing template configurations.',
  },
  {
    id: 'detect_uae',
    label: 'Detect Ultimate Addons',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should detect Ultimate Addons for Elementor (Brainstorm Force) Free/Pro.',
  },
  {
    id: 'list_uae_widgets',
    label: 'List UAE widgets',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should list all widgets provided by Ultimate Addons.',
  },
  {
    id: 'detect_powerpack',
    label: 'Detect PowerPack',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should detect PowerPack for Elementor (Free/Pro).',
  },
  {
    id: 'list_powerpack_widgets',
    label: 'List PowerPack widgets',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should list all widgets provided by PowerPack.',
  },
  {
    id: 'detect_happy_addons',
    label: 'Detect Happy Addons',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should detect Happy Addons for Elementor.',
  },
  {
    id: 'list_happy_addons_widgets',
    label: 'List Happy Addons widgets',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should list all widgets provided by Happy Addons.',
  },
  {
    id: 'detect_elementskit',
    label: 'Detect ElementsKit',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should detect ElementsKit (including Mega Menu detection).',
  },
  {
    id: 'list_elementskit_widgets',
    label: 'List ElementsKit widgets',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should list all widgets provided by ElementsKit.',
  },
  {
    id: 'detect_premium_addons',
    label: 'Detect Premium Addons',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should detect Premium Addons for Elementor.',
  },
  {
    id: 'list_premium_addons_widgets',
    label: 'List Premium Addons widgets',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should list all widgets provided by Premium Addons.',
  },
  {
    id: 'detect_the_plus_addons',
    label: 'Detect The Plus Addons',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should detect The Plus Addons for Elementor.',
  },
  {
    id: 'list_the_plus_addons_widgets',
    label: 'List The Plus Addons widgets',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should list all widgets provided by The Plus Addons.',
  },
  {
    id: 'analyze_ea_usage',
    label: 'Analyze EA usage',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should analyze usage patterns of Essential Addons widgets across the site.',
  },
  {
    id: 'optimize_ea_config',
    label: 'Optimize EA config',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should suggest optimizations for Essential Addons configuration and performance.',
  },
  {
    id: 'wizard_essential_addons',
    label: 'Essential Addons wizard',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Essential Addons module recommendations.',
  },
  {
    id: 'analyze_jet_usage',
    label: 'Analyze JetEngine usage',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should analyze usage patterns of Crocoblock/JetEngine components across the site.',
  },
  {
    id: 'get_jet_query_builders',
    label: 'Get JetEngine query builders',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should list JetEngine query builder configurations for dynamic content.',
  },
  {
    id: 'wizard_crocoblock',
    label: 'Crocoblock wizard',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Crocoblock module recommendations.',
  },
  {
    id: 'analyze_uae_usage',
    label: 'Analyze UAE usage',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should analyze usage patterns of Ultimate Addons widgets across the site.',
  },
  {
    id: 'wizard_uae',
    label: 'Ultimate Addons wizard',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Ultimate Addons module recommendations.',
  },
  {
    id: 'analyze_powerpack_usage',
    label: 'Analyze PowerPack usage',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should analyze usage patterns of PowerPack widgets across the site.',
  },
  {
    id: 'optimize_powerpack_config',
    label: 'Optimize PowerPack config',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should suggest optimizations for PowerPack configuration and performance.',
  },
  {
    id: 'wizard_powerpack',
    label: 'PowerPack wizard',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for PowerPack module recommendations.',
  },
  {
    id: 'analyze_happy_addons_usage',
    label: 'Analyze Happy Addons usage',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should analyze usage patterns of Happy Addons widgets across the site.',
  },
  {
    id: 'optimize_happy_addons_config',
    label: 'Optimize Happy Addons config',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should suggest optimizations for Happy Addons configuration and performance.',
  },
  {
    id: 'wizard_happy_addons',
    label: 'Happy Addons wizard',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Happy Addons module recommendations.',
  },
  {
    id: 'analyze_elementskit_usage',
    label: 'Analyze ElementsKit usage',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should analyze usage patterns of ElementsKit widgets across the site.',
  },
  {
    id: 'optimize_elementskit_config',
    label: 'Optimize ElementsKit config',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should suggest optimizations for ElementsKit configuration and performance.',
  },
  {
    id: 'wizard_elementskit',
    label: 'ElementsKit wizard',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for ElementsKit module recommendations.',
  },
  {
    id: 'analyze_premium_addons_usage',
    label: 'Analyze Premium Addons usage',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should analyze usage patterns of Premium Addons widgets across the site.',
  },
  {
    id: 'optimize_premium_addons_config',
    label: 'Optimize Premium Addons config',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should suggest optimizations for Premium Addons configuration and performance.',
  },
  {
    id: 'wizard_premium_addons',
    label: 'Premium Addons wizard',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for Premium Addons module recommendations.',
  },
  {
    id: 'analyze_the_plus_addons_usage',
    label: 'Analyze The Plus Addons usage',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should analyze usage patterns of The Plus Addons widgets across the site.',
  },
  {
    id: 'optimize_the_plus_addons_config',
    label: 'Optimize The Plus Addons config',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should suggest optimizations for The Plus Addons configuration and performance.',
  },
  {
    id: 'wizard_the_plus_addons',
    label: 'The Plus Addons wizard',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for The Plus Addons module recommendations.',
  },
  {
    id: 'analyze_addon_overlap',
    label: 'Analyze addon overlap',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should analyze widget overlap and redundancy across installed Elementor add‑ons.',
  },
  {
    id: 'widget_census',
    label: 'Widget census',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should provide a comprehensive census of all Elementor widgets (core and add‑ons) with activation and usage stats.',
  },
  {
    id: 'addon_ecosystem_wizard',
    label: 'Addon ecosystem wizard',
    tier: 'advanced',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Internal diagnostic wizard for overall Elementor add‑on ecosystem recommendations.',
  },
  { id: 'get_voxel_status', label: 'Get Voxel status', tier: 'free', visibility: 'public', kind: 'tool', rationale: 'Free should detect Voxel plugin presence and surface version, product-type count, and post-type summary.' },
  { id: 'list_voxel_post_types', label: 'List Voxel post types', tier: 'free', visibility: 'public', kind: 'tool', rationale: 'Free should surface all Voxel dynamic post types with field counts, template assignments, and visibility.' },
  { id: 'get_voxel_post_type', label: 'Get Voxel post type', tier: 'free', visibility: 'public', kind: 'tool', rationale: 'Free should expose detailed Voxel post type configuration, fields, and templates for a single CPT.' },
  { id: 'list_voxel_taxonomies', label: 'List Voxel taxonomies', tier: 'free', visibility: 'public', kind: 'tool', rationale: 'Free should surface all registered Voxel taxonomies including dynamic categories and filters.' },
  { id: 'list_voxel_product_types', label: 'List Voxel product types', tier: 'free', visibility: 'public', kind: 'tool', rationale: 'Free should surface all Voxel product types with pricing-model configuration and linked post types.' },
  { id: 'get_voxel_settings', label: 'Get Voxel settings', tier: 'free', visibility: 'public', kind: 'tool', rationale: 'Free should expose the active Voxel plugin settings snapshot for inspection and documentation.' },
  { id: 'get_voxel_health', label: 'Get Voxel health', tier: 'free', visibility: 'public', kind: 'tool', rationale: 'Free should surface Voxel plugin health, connectivity, index status, and API availability.' },
  { id: 'analyze_composition_requirements', label: 'Analyze composition requirements', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should surface AI composition requirement analysis for template and page assembly.' },
  { id: 'analyze_content_patterns', label: 'Analyze content patterns', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should surface content usage, taxonomy, and template-application patterns across the site.' },
  { id: 'compose_templates', label: 'Compose templates', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should assemble new templates from existing sections and imported library assets.' },
  { id: 'critique_composition', label: 'Critique composition', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should critique AI-assisted template/page compositions against brand, accessibility, and consistency rules.' },
  { id: 'generate_ai_composition', label: 'Generate AI composition', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should generate ready-to-apply page and template compositions from content briefs and design instructions.' },
  { id: 'generate_content_recommendations', label: 'Generate content recommendations', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should analyse the site and suggest content, taxonomy, and template structure improvements.' },
  { id: 'match_templates_to_requirements', label: 'Match templates to requirements', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should match requirement descriptions to the best-fitting existing templates or suggest composites.' },
  { id: 'optimize_content_strategy', label: 'Optimize content strategy', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should analyse content gaps, freshness, and taxonomy coverage and suggest a prioritised content plan.' },
  { id: 'optimize_existing_composition', label: 'Optimize existing composition', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should suggest layout, widget-ordering, and container-structure improvements for existing pages.' },
  { id: 'approve_content', label: 'Approve content', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should support editorial approval for staged content before promotion to production.' },
  { id: 'create_approval_workflow', label: 'Create approval workflow', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should offer configurable approval pipelines for editorial and permission-guarded content workflows.' },
  { id: 'create_content_workflow', label: 'Create content workflow', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should create re-usable editorial workflows with stages, gates, and auto-promotion rules.' },
  { id: 'get_workflow_status', label: 'Get workflow status', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should surface active workflow execution status, pending stages, and outcome logs.' },
  { id: 'list_scheduled_publishes', label: 'List scheduled publishes', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should list all content items scheduled for future publication across post types.' },
  { id: 'monitor_approvals', label: 'Monitor approvals', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should surface the current state of all open approval workflows with assignees and SLA status.' },
  { id: 'promote_content_to_next_stage', label: 'Promote content to next stage', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should advance content through each editorial stage in a configured workflow.' },
  { id: 'request_content_approval', label: 'Request content approval', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should let operators submit staged content for reviewer approval with optional notes and urgency.' },
  { id: 'schedule_content_publish', label: 'Schedule content publish', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should schedule currently draft or approved content for future publication with a date/time.' },
  { id: 'stage_content_to_environment', label: 'Stage content to environment', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should stage draft content to a remote environment for preview and approval workflows.' },
  { id: 'start_workflow_execution', label: 'Start workflow execution', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should trigger execution of a defined multi-step content- or template- workflow.' },
  { id: 'cleanup_drafts', label: 'Cleanup drafts', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should allow safe bulk removal of abandoned draft posts, pages, templates, and change-queue entries.' },
  { id: 'get_environment_status', label: 'Get environment status', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should surface a live health summary for each configured environment (production, staging, local).' },
  { id: 'list_environments', label: 'List environments', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should list all configured environments with labels, URLs, and connectivity state.' },
  { id: 'promote_environment', label: 'Promote environment', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should promote assets from staging to production with validation, diff preview, and rollback option.' },
  { id: 'refresh_staging', label: 'Refresh staging', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should sync staging from production with data-overwrite safety confirmations.' },
  { id: 'switch_environment', label: 'Switch environment', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should let the current session target a different configured environment for read and write operations.' },
  { id: 'assign_role_to_user', label: 'Assign role to user', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should let operators assign WordPress roles and MCP RBAC roles to individual users.' },
  { id: 'audit_permission_changes', label: 'Audit permission changes', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should surface an audit log of all permission and RBAC changes across environments.' },
  { id: 'audit_rbac_compliance', label: 'Audit RBAC compliance', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should check that active role grants and RBAC rules match the approved policy baseline.' },
  { id: 'check_user_permission', label: 'Check user permission', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should verify whether a user holds a specific capability before guarded actions.' },
  { id: 'configure_rbac_policy', label: 'Configure RBAC policy', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should let operators define and apply RBAC policy rules across environments.' },
  { id: 'create_permission_rule', label: 'Create permission rule', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should add individual allow/deny RBAC rules scoped to users, roles, or API keys.' },
  { id: 'create_user_role', label: 'Create user role', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should define custom RBAC roles across the MCP client surface.' },
  { id: 'list_user_permissions', label: 'List user permissions', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should list all MCP users and their assigned roles, capabilities, and API-key bindings.' },
  { id: 'manage_role_hierarchy', label: 'Manage role hierarchy', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should re-order custom RBAC role inheritance chains and preview effective permissions.' },
  { id: 'update_role_permissions', label: 'Update role permissions', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should add or remove capabilities from an MCP RBAC role definition.' },
  { id: 'create_template_with_versioning', label: 'Create template with versioning', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should create templates with built-in version tracking and rollback snapshots.' },
  { id: 'extract_template_components', label: 'Extract template components', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should extract sections, widgets, and container layout from existing templates for composition reuse.' },
  { id: 'get_template_versions', label: 'Get template versions', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should list all saved versions of a template with metadata, diffs, and restore options.' },
  { id: 'list_templates_enhanced', label: 'List templates enhanced', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should list templates with enriched metadata (conditions, usage count, version count, last editor).' },
  { id: 'merge_template_sections', label: 'Merge template sections', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should merge sections from multiple templates into a new composite template with conflict resolution.' },
  { id: 'restore_template_version', label: 'Restore template version', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should roll back a template to a prior saved version with confirmation and optional backup of current.' },
  { id: 'search_templates_advanced', label: 'Search templates advanced', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should provide advanced template search with filters for type, condition, widget, usage, and version.' },
  { id: 'update_template_with_versioning', label: 'Update template with versioning', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should update a template and automatically create a versioned snapshot for audit and rollback.' },
  { id: 'list_form_templates', label: 'List form templates', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should surface available Elementor Form field templates and pre-built form patterns.' },
  { id: 'list_forms', label: 'List forms', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should enumerate Elementor Pro forms, their field structures, and active integrations.' },
  { id: 'queue_cleanup', label: 'Queue cleanup', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should remove stale, orphaned, or applied change-queue entries safely with audit trail.' },
  { id: 'queue_stats', label: 'Queue stats', tier: 'advanced', visibility: 'public', kind: 'tool', rationale: 'Advanced should surface change-queue metrics: pending, approved, rejected, per-environment, per-user.' },
];

const GOVERNANCE_LEVEL_OVERRIDES: Record<string, 'L0' | 'L1' | 'L2' | 'L3'> = {
  // L3 - Deletions and high-risk
  'delete_template': 'L3',
  'delete_post': 'L3',
  'delete_menu': 'L3',
  'delete_menu_item': 'L3',
  'delete_term': 'L3',
  'delete_media': 'L3',
  'audit_unused_media': 'L3',
  'delete_product': 'L3',
  'queue_change': 'L3',
  // L2 - Impactful writes
  'set_global_colors': 'L2',
  'set_global_typography': 'L2',
  'set_site_logo': 'L2',
  'update_template_data': 'L2',
  'update_page_data': 'L2',
  'compose_page_from_templates': 'L2',
  'migrate_form': 'L2',
  'import_external_data': 'L2',
  'mass_export': 'L2',
  'save_page_section_as_template': 'L2',
  'save_full_page_as_template': 'L2',
  'set_site_context': 'L2',
  'update_seo_meta': 'L2',
  'update_site_settings': 'L2',
  'flush_elementor_cache': 'L2',
  'optimize_elementor_assets': 'L2',
  'clean_database': 'L2',
  'test_plugin_conflict': 'L2',
  'wizard_brand_setup': 'L2',
  'creator_mode': 'L2',
  'wizard_theme_builder': 'L2',
  'advanced_creator_mode': 'L2',
  'import_premium_library_asset': 'L2',
  'plan_brand_adaptation': 'L2',
  'plan_rebuild_strategy': 'L2',
  'critique_rebuild_strategy': 'L2',
  'critique_elementor_output': 'L2',
  'suggest_pipeline_path': 'L2',
  'create_form_advanced': 'L2',
  'batch_translate_strings': 'L2',
  'translate_media_metadata': 'L2',
  'scan_accessibility': 'L2',
  'create_product': 'L2',
  'update_product': 'L2',
  'update_order_status': 'L2',
  'generate_critical_css': 'L2',
  'manage_product_category': 'L2',
  'update_store_settings': 'L2',
  'setup_woocommerce_pages': 'L2',
  // L1 - Safe writes
  'create_template': 'L1',
  'update_template': 'L1',
  'rename_template': 'L1',
  'duplicate_template': 'L1',
  'bulk_rename': 'L1',
  'set_category': 'L1',
  'set_tags': 'L1',
  'create_page': 'L1',
  'create_post': 'L1',
  'create_form_light': 'L1',
  'update_post_meta': 'L1',
  'create_menu': 'L1',
  'create_menu_item': 'L1',
  'update_menu_item': 'L1',
  'assign_menu_location': 'L1',
  'create_term': 'L1',
  'update_term': 'L1',
  'update_media': 'L1',
};

export const GOVERNANCE_LEVELS: Record<string, 'L0' | 'L1' | 'L2' | 'L3'> = Object.fromEntries(
  TOOL_TIER_ASSIGNMENTS.map(assignment => [
    assignment.id,
    GOVERNANCE_LEVEL_OVERRIDES[assignment.id] || 'L0'
  ])
);

export const TIER_BOUNDARY_CASES: TierBoundaryCase[] = [
  {
    id: 'theme-builder-boundary',
    decision: 'Keep wizard_theme_builder in Advanced.',
    rationale: 'Theme Builder changes site-wide structural delivery and should mark the step up from creator-light to deeper workflow control.',
    affectedSurfaces: ['wizard_theme_builder', 'plan_rebuild_strategy'],
  },
  {
    id: 'local-multi-site-vs-studio',
    decision: 'Keep list_sites and switch_site in Free.',
    rationale: 'Local operator switching is not the same as Studio cloud reuse or cross-site delivery orchestration.',
    affectedSurfaces: ['list_sites', 'switch_site', 'suggest_pipeline_path'],
  },
  {
    id: 'delete-template-in-free',
    decision: 'Keep delete_template in Free.',
    rationale: 'Free should feel operationally real; governance and scoped API keys are the safety mechanism rather than artificial crippleware.',
    affectedSurfaces: ['delete_template', 'queue_change'],
  },
  {
    id: 'control-plane-seed',
    decision: 'Treat suggest_pipeline_path as studio_future even though the seed exists in code.',
    rationale: 'It is strategically closer to future orchestration than to the current public Free or private Advanced promise.',
    affectedSurfaces: ['suggest_pipeline_path'],
  },
  {
    id: 'bootstrap-front-door',
    decision: 'Keep route_intent_wizard and plan_stack_bootstrap in Free.',
    rationale: 'The scenario-first front door is part of the public Free promise and should help users before deeper Advanced workflow logic begins.',
    affectedSurfaces: ['route_intent_wizard', 'plan_stack_bootstrap', 'get_advanced_recommendations'],
  },
  {
    id: 'free-runtime-wizard-families',
    decision: 'Keep new-site lite, stack bootstrap, extension lite, relaunch lite, and optimization lite runtime wizards in Free.',
    rationale: 'These flows are the concrete scenario-family execution layer behind the Free front door and should stay public before deeper Advanced orchestration begins.',
    affectedSurfaces: ['wizard_new_site_lite', 'wizard_stack_bootstrap', 'wizard_extension_lite', 'wizard_relaunch_lite', 'wizard_optimization_lite', 'advanced_creator_mode'],
  },
  {
    id: 'advanced-scenario-front-door',
    decision: 'Keep route_advanced_scenario in Advanced.',
    rationale: 'Advanced should expose a scenario-first private entry layer for deep relaunch, migration, premium rollout, and critique paths rather than only a deeper workflow tool shelf.',
    affectedSurfaces: ['route_advanced_scenario', 'advanced_creator_mode', 'get_advanced_recommendations'],
  },
];

const TOOL_TIER_MAP = new Map(
  TOOL_TIER_ASSIGNMENTS.map((assignment) => [assignment.id, assignment]),
);

export function getToolTierAssignment(toolName: string): ProductSurfaceAssignment | undefined {
  return TOOL_TIER_MAP.get(toolName);
}

export function findUnassignedToolNames(): string[] {
  return REGISTERED_TOOL_NAMES.filter((toolName) => !TOOL_TIER_MAP.has(toolName));
}
